---
# Tasks for Docker CE on Debain systems.

- name: remove existing docker installations
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - "docker"
    - "docker-engine"
    - "docker.io"

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "software-properties-common"

- name: add docker apt key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: install docker community edition
  apt:
    name: "docker-ce"
    state: latest
    update_cache: yes
    